spring.application.name=AutoLix

# CONFIGURARE DINAMIC? PENTRU CLOUD (Railway)
# Dac? MYSQL_URL nu exist? (pe localhost), va folosi varianta de dup? colon ":"
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/parc_auto?createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPI & HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PORTUL DINAMIC (Critic pentru hosting)
server.port=${PORT:8081}

# FILE UPLOADS
# ATEN?IE: Pe Railway, fi?ierele salvate în ./uploads vor disp?rea la restart!
app.upload.dir=${UPLOAD_DIR:./uploads}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# TOMCAT SETTINGS
server.tomcat.max-parameters=20000
server.tomcat.max-part-count=50